# Reproducibility guard for the shipped datasets.
#
# The invariant is NOT "every dataset carries the current package version" --
# that one is only satisfiable by rewriting metadata on every version bump,
# which would assert that the new version generated numbers it never ran, and
# would change the bytes of files that are in fact unchanged.
#
# The honest invariant, enforced below, is that every shipped dataset is fully
# accounted for:
#   * it declares the version that generated it, and that version is not newer
#     than the installed package (no data from the future);
#   * it is listed in MANIFEST.csv (release identity) with matching metadata;
#   * it is listed in SHA256SUMS (content identity) with a matching checksum.
# Regenerate both manifests with data-raw/999_manifest.R.

extdata_dir <- function() system.file("extdata", package = "lcdaGRASP")

rds_files <- function() {
  list.files(extdata_dir(), pattern = "\\.rds$", full.names = TRUE)
}

skip_if_no_extdata <- function() {
  skip_if(!nzchar(extdata_dir()) || length(rds_files()) == 0,
          "no extdata datasets installed")
}

test_that("no shipped dataset was generated by a newer package version", {
  skip_if_no_extdata()
  ver <- utils::packageVersion("lcdaGRASP")
  bad <- vapply(rds_files(), function(f) {
    m <- readRDS(f)$meta
    v <- if (is.null(m$pkg_version)) NA_character_ else as.character(m$pkg_version)[1]
    ok <- !is.na(v) &&
      !inherits(try(numeric_version(v), silent = TRUE), "try-error") &&
      numeric_version(v) <= ver
    if (ok) NA_character_ else paste0(basename(f), " (", v, ")")
  }, character(1))
  bad <- bad[!is.na(bad)]
  expect_true(
    length(bad) == 0,
    info = paste0("RDS with a missing or future meta$pkg_version (installed ",
                  ver, "): ", paste(bad, collapse = ", "))
  )
})

test_that("MANIFEST.csv covers every shipped dataset and agrees with its metadata", {
  skip_if_no_extdata()
  path <- file.path(extdata_dir(), "MANIFEST.csv")
  skip_if(!file.exists(path), "no MANIFEST.csv")
  mf <- utils::read.csv(path, stringsAsFactors = FALSE, colClasses = "character")

  expect_setequal(names(mf),
                  c("dataset", "generated_on", "generated_by", "first_release"))

  on_disk <- sub("\\.rds$", "", basename(rds_files()))
  expect_setequal(mf$dataset, on_disk)          # no missing rows, no orphans

  ver <- utils::packageVersion("lcdaGRASP")
  bad <- character()
  for (i in seq_len(nrow(mf))) {
    nm <- mf$dataset[i]
    m  <- readRDS(file.path(extdata_dir(), paste0(nm, ".rds")))$meta
    if (!identical(as.character(m$pkg_version)[1], mf$generated_by[i]))
      bad <- c(bad, paste0(nm, ": generated_by"))
    if (!identical(as.character(m$generated_on)[1], mf$generated_on[i]))
      bad <- c(bad, paste0(nm, ": generated_on"))
    # a dataset cannot first ship in a version that does not exist yet
    if (numeric_version(mf$first_release[i]) > ver)
      bad <- c(bad, paste0(nm, ": first_release ", mf$first_release[i], " > ", ver))
  }
  expect_true(
    length(bad) == 0,
    info = paste0("MANIFEST.csv disagrees with the data: ",
                  paste(bad, collapse = ", "))
  )
})

test_that("SHA256SUMS covers every shipped dataset with a matching checksum", {
  skip_if_no_extdata()
  sums <- file.path(extdata_dir(), "SHA256SUMS")
  skip_if(!file.exists(sums), "no SHA256SUMS manifest")

  lines <- readLines(sums, warn = FALSE)
  lines <- lines[nzchar(trimws(lines))]
  listed <- sub("^[0-9a-f]{64}[[:space:]]+\\*?", "", lines)
  hashes <- stats::setNames(sub("[[:space:]].*$", "", lines), listed)
  expect_setequal(listed, basename(rds_files()))

  # tools::sha256sum() is recent; skip the byte-level check on older R.
  skip_if_not(exists("sha256sum", where = asNamespace("tools")),
              "tools::sha256sum() not available")
  fs  <- rds_files()
  got <- unname(tools::sha256sum(fs))
  mismatch <- basename(fs)[got != unname(hashes[basename(fs)])]
  expect_true(
    length(mismatch) == 0,
    info = paste0("checksum mismatch: ", paste(mismatch, collapse = ", "))
  )
})

test_that("lcda_provenance separates generating version from shipped version", {
  skip_if(!nzchar(extdata_dir()) ||
            !file.exists(file.path(extdata_dir(), "repro_summary.rds")),
          "extdata not installed")
  p <- lcda_provenance("repro_summary")
  expect_s3_class(p, "data.frame")
  expect_true(all(c("dataset", "generated_by", "generated_on",
                    "first_release", "shipped_in", "sha256") %in% names(p)))
  # the copy you are running is always the installed version ...
  expect_identical(p$shipped_in, as.character(utils::packageVersion("lcdaGRASP")))
  # ... while the generating version is whatever actually produced the numbers
  expect_false(is.na(p$generated_by))
  expect_true(numeric_version(p$generated_by) <=
                utils::packageVersion("lcdaGRASP"))
  skip_if(!file.exists(file.path(extdata_dir(), "SHA256SUMS")), "no SHA256SUMS")
  expect_match(p$sha256, "^[0-9a-f]{64}$")
  skip_if(!file.exists(file.path(extdata_dir(), "MANIFEST.csv")), "no MANIFEST.csv")
  expect_match(p$first_release, "^[0-9]+\\.[0-9]+")
})

test_that("lcda_provenance returns NULL for an unknown dataset", {
  expect_null(suppressMessages(lcda_provenance("does_not_exist_xyz")))
})
