// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// modularity_cpp
double modularity_cpp(IntegerVector adj_indptr, IntegerVector adj_indices, IntegerVector membership, NumericVector adj_weights);
RcppExport SEXP _lcdaGRASP_modularity_cpp(SEXP adj_indptrSEXP, SEXP adj_indicesSEXP, SEXP membershipSEXP, SEXP adj_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indptr(adj_indptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indices(adj_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type membership(membershipSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adj_weights(adj_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(modularity_cpp(adj_indptr, adj_indices, membership, adj_weights));
    return rcpp_result_gen;
END_RCPP
}
// community_affinity_cpp
NumericMatrix community_affinity_cpp(IntegerVector adj_indptr, IntegerVector adj_indices, IntegerVector membership, int d, NumericVector adj_weights);
RcppExport SEXP _lcdaGRASP_community_affinity_cpp(SEXP adj_indptrSEXP, SEXP adj_indicesSEXP, SEXP membershipSEXP, SEXP dSEXP, SEXP adj_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indptr(adj_indptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indices(adj_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type membership(membershipSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adj_weights(adj_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(community_affinity_cpp(adj_indptr, adj_indices, membership, d, adj_weights));
    return rcpp_result_gen;
END_RCPP
}
// delta_modularity_cpp
double delta_modularity_cpp(NumericMatrix S, int i, int t, int current_comm, NumericVector deg, double two_m);
RcppExport SEXP _lcdaGRASP_delta_modularity_cpp(SEXP SSEXP, SEXP iSEXP, SEXP tSEXP, SEXP current_commSEXP, SEXP degSEXP, SEXP two_mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type current_comm(current_commSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type deg(degSEXP);
    Rcpp::traits::input_parameter< double >::type two_m(two_mSEXP);
    rcpp_result_gen = Rcpp::wrap(delta_modularity_cpp(S, i, t, current_comm, deg, two_m));
    return rcpp_result_gen;
END_RCPP
}
// update_affinities_inplace_cpp
void update_affinities_inplace_cpp(NumericMatrix S, IntegerVector adj_indptr, IntegerVector adj_indices, int i, int c_from, int c_to, NumericVector deg, double two_m, NumericVector adj_weights);
RcppExport SEXP _lcdaGRASP_update_affinities_inplace_cpp(SEXP SSEXP, SEXP adj_indptrSEXP, SEXP adj_indicesSEXP, SEXP iSEXP, SEXP c_fromSEXP, SEXP c_toSEXP, SEXP degSEXP, SEXP two_mSEXP, SEXP adj_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type S(SSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indptr(adj_indptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indices(adj_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type c_from(c_fromSEXP);
    Rcpp::traits::input_parameter< int >::type c_to(c_toSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type deg(degSEXP);
    Rcpp::traits::input_parameter< double >::type two_m(two_mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adj_weights(adj_weightsSEXP);
    update_affinities_inplace_cpp(S, adj_indptr, adj_indices, i, c_from, c_to, deg, two_m, adj_weights);
    return R_NilValue;
END_RCPP
}
// local_search_cpp
List local_search_cpp(IntegerVector adj_indptr, IntegerVector adj_indices, IntegerVector membership_in, int d, NumericVector adj_weights, double tol, int max_iter);
RcppExport SEXP _lcdaGRASP_local_search_cpp(SEXP adj_indptrSEXP, SEXP adj_indicesSEXP, SEXP membership_inSEXP, SEXP dSEXP, SEXP adj_weightsSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indptr(adj_indptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indices(adj_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type membership_in(membership_inSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adj_weights(adj_weightsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(local_search_cpp(adj_indptr, adj_indices, membership_in, d, adj_weights, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// vnmi_local_search_cpp
List vnmi_local_search_cpp(IntegerVector adj_indptr, IntegerVector adj_indices, IntegerVector membership_in, int d, NumericVector adj_weights, int n_prime, double eps, int max_passes, int seed);
RcppExport SEXP _lcdaGRASP_vnmi_local_search_cpp(SEXP adj_indptrSEXP, SEXP adj_indicesSEXP, SEXP membership_inSEXP, SEXP dSEXP, SEXP adj_weightsSEXP, SEXP n_primeSEXP, SEXP epsSEXP, SEXP max_passesSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indptr(adj_indptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indices(adj_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type membership_in(membership_inSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adj_weights(adj_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type n_prime(n_primeSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type max_passes(max_passesSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(vnmi_local_search_cpp(adj_indptr, adj_indices, membership_in, d, adj_weights, n_prime, eps, max_passes, seed));
    return rcpp_result_gen;
END_RCPP
}
// similarity_hpi_cpp
NumericVector similarity_hpi_cpp(IntegerVector adj_indptr, IntegerVector adj_indices, int L, IntegerVector pool);
RcppExport SEXP _lcdaGRASP_similarity_hpi_cpp(SEXP adj_indptrSEXP, SEXP adj_indicesSEXP, SEXP LSEXP, SEXP poolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indptr(adj_indptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indices(adj_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pool(poolSEXP);
    rcpp_result_gen = Rcpp::wrap(similarity_hpi_cpp(adj_indptr, adj_indices, L, pool));
    return rcpp_result_gen;
END_RCPP
}
// similarity_dice_cpp
NumericVector similarity_dice_cpp(IntegerVector adj_indptr, IntegerVector adj_indices, int L, IntegerVector pool);
RcppExport SEXP _lcdaGRASP_similarity_dice_cpp(SEXP adj_indptrSEXP, SEXP adj_indicesSEXP, SEXP LSEXP, SEXP poolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indptr(adj_indptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indices(adj_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pool(poolSEXP);
    rcpp_result_gen = Rcpp::wrap(similarity_dice_cpp(adj_indptr, adj_indices, L, pool));
    return rcpp_result_gen;
END_RCPP
}
// similarity_jaccard_cpp
NumericVector similarity_jaccard_cpp(IntegerVector adj_indptr, IntegerVector adj_indices, int L, IntegerVector pool);
RcppExport SEXP _lcdaGRASP_similarity_jaccard_cpp(SEXP adj_indptrSEXP, SEXP adj_indicesSEXP, SEXP LSEXP, SEXP poolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indptr(adj_indptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indices(adj_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pool(poolSEXP);
    rcpp_result_gen = Rcpp::wrap(similarity_jaccard_cpp(adj_indptr, adj_indices, L, pool));
    return rcpp_result_gen;
END_RCPP
}
// nce_node_cpp
double nce_node_cpp(int kv, int n);
RcppExport SEXP _lcdaGRASP_nce_node_cpp(SEXP kvSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kv(kvSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(nce_node_cpp(kv, n));
    return rcpp_result_gen;
END_RCPP
}
// nce_score_cpp
double nce_score_cpp(IntegerVector leader_degrees, int n);
RcppExport SEXP _lcdaGRASP_nce_score_cpp(SEXP leader_degreesSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type leader_degrees(leader_degreesSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(nce_score_cpp(leader_degrees, n));
    return rcpp_result_gen;
END_RCPP
}
// nce_local_cpp
double nce_local_cpp(IntegerVector adj_indptr, IntegerVector adj_indices, IntegerVector membership, IntegerVector leaders);
RcppExport SEXP _lcdaGRASP_nce_local_cpp(SEXP adj_indptrSEXP, SEXP adj_indicesSEXP, SEXP membershipSEXP, SEXP leadersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indptr(adj_indptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indices(adj_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type membership(membershipSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type leaders(leadersSEXP);
    rcpp_result_gen = Rcpp::wrap(nce_local_cpp(adj_indptr, adj_indices, membership, leaders));
    return rcpp_result_gen;
END_RCPP
}
// eigen_centrality_cpp
NumericVector eigen_centrality_cpp(IntegerVector adj_indptr, IntegerVector adj_indices, int max_iter, double tol);
RcppExport SEXP _lcdaGRASP_eigen_centrality_cpp(SEXP adj_indptrSEXP, SEXP adj_indicesSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indptr(adj_indptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type adj_indices(adj_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_centrality_cpp(adj_indptr, adj_indices, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// rcl_max_cpp
IntegerVector rcl_max_cpp(NumericVector scores, double alpha);
RcppExport SEXP _lcdaGRASP_rcl_max_cpp(SEXP scoresSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcl_max_cpp(scores, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcl_min_cpp
IntegerVector rcl_min_cpp(NumericVector scores, double alpha);
RcppExport SEXP _lcdaGRASP_rcl_min_cpp(SEXP scoresSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcl_min_cpp(scores, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lcdaGRASP_modularity_cpp", (DL_FUNC) &_lcdaGRASP_modularity_cpp, 4},
    {"_lcdaGRASP_community_affinity_cpp", (DL_FUNC) &_lcdaGRASP_community_affinity_cpp, 5},
    {"_lcdaGRASP_delta_modularity_cpp", (DL_FUNC) &_lcdaGRASP_delta_modularity_cpp, 6},
    {"_lcdaGRASP_update_affinities_inplace_cpp", (DL_FUNC) &_lcdaGRASP_update_affinities_inplace_cpp, 9},
    {"_lcdaGRASP_local_search_cpp", (DL_FUNC) &_lcdaGRASP_local_search_cpp, 7},
    {"_lcdaGRASP_vnmi_local_search_cpp", (DL_FUNC) &_lcdaGRASP_vnmi_local_search_cpp, 9},
    {"_lcdaGRASP_similarity_hpi_cpp", (DL_FUNC) &_lcdaGRASP_similarity_hpi_cpp, 4},
    {"_lcdaGRASP_similarity_dice_cpp", (DL_FUNC) &_lcdaGRASP_similarity_dice_cpp, 4},
    {"_lcdaGRASP_similarity_jaccard_cpp", (DL_FUNC) &_lcdaGRASP_similarity_jaccard_cpp, 4},
    {"_lcdaGRASP_nce_node_cpp", (DL_FUNC) &_lcdaGRASP_nce_node_cpp, 2},
    {"_lcdaGRASP_nce_score_cpp", (DL_FUNC) &_lcdaGRASP_nce_score_cpp, 2},
    {"_lcdaGRASP_nce_local_cpp", (DL_FUNC) &_lcdaGRASP_nce_local_cpp, 4},
    {"_lcdaGRASP_eigen_centrality_cpp", (DL_FUNC) &_lcdaGRASP_eigen_centrality_cpp, 4},
    {"_lcdaGRASP_rcl_max_cpp", (DL_FUNC) &_lcdaGRASP_rcl_max_cpp, 2},
    {"_lcdaGRASP_rcl_min_cpp", (DL_FUNC) &_lcdaGRASP_rcl_min_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_lcdaGRASP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
