# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

modularity_cpp <- function(adj_indptr, adj_indices, membership, adj_weights) {
    .Call(`_lcdaGRASP_modularity_cpp`, adj_indptr, adj_indices, membership, adj_weights)
}

community_affinity_cpp <- function(adj_indptr, adj_indices, membership, d, adj_weights) {
    .Call(`_lcdaGRASP_community_affinity_cpp`, adj_indptr, adj_indices, membership, d, adj_weights)
}

delta_modularity_cpp <- function(S, i, t, current_comm, deg, two_m) {
    .Call(`_lcdaGRASP_delta_modularity_cpp`, S, i, t, current_comm, deg, two_m)
}

update_affinities_inplace_cpp <- function(S, adj_indptr, adj_indices, i, c_from, c_to, deg, two_m, adj_weights) {
    invisible(.Call(`_lcdaGRASP_update_affinities_inplace_cpp`, S, adj_indptr, adj_indices, i, c_from, c_to, deg, two_m, adj_weights))
}

local_search_cpp <- function(adj_indptr, adj_indices, membership_in, d, adj_weights, tol = 1e-12, max_iter = 1000000L) {
    .Call(`_lcdaGRASP_local_search_cpp`, adj_indptr, adj_indices, membership_in, d, adj_weights, tol, max_iter)
}

vnmi_local_search_cpp <- function(adj_indptr, adj_indices, membership_in, d, adj_weights, n_prime = 300L, eps = 1e-4, max_passes = 200L) {
    .Call(`_lcdaGRASP_vnmi_local_search_cpp`, adj_indptr, adj_indices, membership_in, d, adj_weights, n_prime, eps, max_passes)
}

similarity_hpi_cpp <- function(adj_indptr, adj_indices, L, pool) {
    .Call(`_lcdaGRASP_similarity_hpi_cpp`, adj_indptr, adj_indices, L, pool)
}

similarity_dice_cpp <- function(adj_indptr, adj_indices, L, pool) {
    .Call(`_lcdaGRASP_similarity_dice_cpp`, adj_indptr, adj_indices, L, pool)
}

similarity_jaccard_cpp <- function(adj_indptr, adj_indices, L, pool) {
    .Call(`_lcdaGRASP_similarity_jaccard_cpp`, adj_indptr, adj_indices, L, pool)
}

nce_node_cpp <- function(kv, n) {
    .Call(`_lcdaGRASP_nce_node_cpp`, kv, n)
}

nce_score_cpp <- function(leader_degrees, n) {
    .Call(`_lcdaGRASP_nce_score_cpp`, leader_degrees, n)
}

nce_local_cpp <- function(adj_indptr, adj_indices, membership, leaders) {
    .Call(`_lcdaGRASP_nce_local_cpp`, adj_indptr, adj_indices, membership, leaders)
}

eigen_centrality_cpp <- function(adj_indptr, adj_indices, max_iter = 1000L, tol = 1e-10) {
    .Call(`_lcdaGRASP_eigen_centrality_cpp`, adj_indptr, adj_indices, max_iter, tol)
}

rcl_max_cpp <- function(scores, alpha) {
    .Call(`_lcdaGRASP_rcl_max_cpp`, scores, alpha)
}

rcl_min_cpp <- function(scores, alpha) {
    .Call(`_lcdaGRASP_rcl_min_cpp`, scores, alpha)
}

